"""add_feedback_table

Revision ID: 02be526d9788
Revises: c170a58bd650
Create Date: 2026-06-22 13:23:25.044338

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "02be526d9788"
down_revision: Union[str, Sequence[str], None] = "c170a58bd650"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column("page_url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["username"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedback_id"), "feedback", ["id"], unique=False)
    op.create_index(
        op.f("ix_project_metadata_id"), "project_metadata", ["id"], unique=False
    )
    op.create_unique_constraint(None, "project_metadata", ["config_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project_metadata", type_="unique")
    op.drop_index(op.f("ix_project_metadata_id"), table_name="project_metadata")
    op.drop_index(op.f("ix_feedback_id"), table_name="feedback")
    op.drop_table("feedback")
    # ### end Alembic commands ###
