"""Add condition column to bom_line table

Revision ID: 4cdfa67125a6
Revises: 51dcc6a3015a
Create Date: 2026-05-25 15:46:12.020453

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4cdfa67125a6"
down_revision: Union[str, Sequence[str], None] = "51dcc6a3015a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bom_line", sa.Column("condition", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bom_line", "condition")
    # ### end Alembic commands ###
