"""Add ventillation columns to configuration table

Revision ID: 5f78f076c92a
Revises: 4cdfa67125a6
Create Date: 2026-05-25 15:58:01.346388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5f78f076c92a"
down_revision: Union[str, Sequence[str], None] = "4cdfa67125a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configuration",
        sa.Column("effective_dp_w", sa.Float(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("req_airflow_m3h", sa.Float(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("def_fan_model", sa.String(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("def_fan_qty", sa.Integer(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("def_grill_model", sa.String(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("def_grill_qty", sa.Integer(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("alt_fan_model", sa.String(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("alt_fan_qty", sa.Integer(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("alt_grill_model", sa.String(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("alt_grill_qty", sa.Integer(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("out_fan_model", sa.String(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("out_fan_qty", sa.Integer(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("out_grill_model", sa.String(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("out_grill_qty", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configuration", "out_grill_qty")
    op.drop_column("configuration", "out_grill_model")
    op.drop_column("configuration", "out_fan_qty")
    op.drop_column("configuration", "out_fan_model")
    op.drop_column("configuration", "alt_grill_qty")
    op.drop_column("configuration", "alt_grill_model")
    op.drop_column("configuration", "alt_fan_qty")
    op.drop_column("configuration", "alt_fan_model")
    op.drop_column("configuration", "def_grill_qty")
    op.drop_column("configuration", "def_grill_model")
    op.drop_column("configuration", "def_fan_qty")
    op.drop_column("configuration", "def_fan_model")
    op.drop_column("configuration", "req_airflow_m3h")
    op.drop_column("configuration", "effective_dp_w")
    # ### end Alembic commands ###
