"""initial_full_schema

Revision ID: 7684c9de6efd
Revises: 
Create Date: 2026-03-19 09:43:53.376494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7684c9de6efd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_catalog',
    sa.Column('accessory_id', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('accessory_category', sa.String(), nullable=True),
    sa.Column('accessory_subcategory', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('product_range', sa.String(), nullable=True),
    sa.Column('nominal_rating_or_size', sa.String(), nullable=True),
    sa.Column('standard_use_case', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('accessory_id')
    )
    op.create_index(op.f('ix_accessory_catalog_accessory_id'), 'accessory_catalog', ['accessory_id'], unique=False)
    op.create_index(op.f('ix_accessory_catalog_part_number'), 'accessory_catalog', ['part_number'], unique=True)
    op.create_table('application_alarm_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('alarm_code_template', sa.String(), nullable=True),
    sa.Column('tag_source_template', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('is_per_load', sa.Boolean(), nullable=True),
    sa.Column('operator_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_alarm_template_id'), 'application_alarm_template', ['id'], unique=False)
    op.create_table('application_io_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('tag_template', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('interface', sa.String(), nullable=True),
    sa.Column('is_per_load', sa.Boolean(), nullable=True),
    sa.Column('required_communication_mode', sa.String(), nullable=True),
    sa.Column('alarm_linked', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_io_template_id'), 'application_io_template', ['id'], unique=False)
    op.create_table('application_option_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('option_category', sa.String(), nullable=True),
    sa.Column('option_name', sa.String(), nullable=True),
    sa.Column('is_base_or_optional', sa.String(), nullable=True),
    sa.Column('spec_text_hint', sa.String(), nullable=True),
    sa.Column('engineering_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_option_matrix_id'), 'application_option_matrix', ['id'], unique=False)
    op.create_table('component_catalog',
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=True),
    sa.Column('generic_description', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('part_family', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('part_number')
    )
    op.create_index(op.f('ix_component_catalog_part_number'), 'component_catalog', ['part_number'], unique=False)
    op.create_table('data_quality_issue',
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('issue_text', sa.String(), nullable=True),
    sa.Column('proposed_action', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_index(op.f('ix_data_quality_issue_issue_id'), 'data_quality_issue', ['issue_id'], unique=False)
    op.create_table('enclosure_option',
    sa.Column('enclosure_option_id', sa.String(), nullable=False),
    sa.Column('layout_dim_h_mm', sa.Integer(), nullable=True),
    sa.Column('layout_dim_w_mm', sa.Integer(), nullable=True),
    sa.Column('layout_dim_d_mm', sa.Integer(), nullable=True),
    sa.Column('catalog_ref', sa.String(), nullable=True),
    sa.Column('catalog_size_hxwxd', sa.String(), nullable=True),
    sa.Column('mounting_type', sa.String(), nullable=True),
    sa.Column('ip_rating', sa.String(), nullable=True),
    sa.Column('ik_rating', sa.String(), nullable=True),
    sa.Column('door_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('enclosure_option_id')
    )
    op.create_index(op.f('ix_enclosure_option_enclosure_option_id'), 'enclosure_option', ['enclosure_option_id'], unique=False)
    op.create_table('series',
    sa.Column('series_id', sa.String(), nullable=False),
    sa.Column('series_name', sa.String(), nullable=True),
    sa.Column('starter_method', sa.String(), nullable=True),
    sa.Column('ats_scope', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index(op.f('ix_series_series_id'), 'series', ['series_id'], unique=False)
    op.create_table('size_class',
    sa.Column('size_class', sa.String(), nullable=False),
    sa.Column('class_rank', sa.Integer(), nullable=True),
    sa.Column('class_description', sa.String(), nullable=True),
    sa.Column('typical_contactor_range', sa.String(), nullable=True),
    sa.Column('branch_current_band_a', sa.String(), nullable=True),
    sa.Column('engineering_note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('size_class')
    )
    op.create_index(op.f('ix_size_class_size_class'), 'size_class', ['size_class'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'User', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('accessory_rule',
    sa.Column('accessory_rule_id', sa.String(), nullable=False),
    sa.Column('series_id', sa.String(), nullable=True),
    sa.Column('size_class', sa.String(), nullable=True),
    sa.Column('rule_scope', sa.String(), nullable=True),
    sa.Column('include_in_default_bom', sa.Boolean(), nullable=True),
    sa.Column('accessory_subcategory', sa.String(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('qty_per_feeder', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('qty_per_panel', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('qty_formula_text', sa.String(), nullable=True),
    sa.Column('design_basis', sa.String(), nullable=True),
    sa.Column('lookup_key', sa.String(), nullable=True),
    sa.Column('engineering_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['part_number'], ['accessory_catalog.part_number'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.series_id'], ),
    sa.PrimaryKeyConstraint('accessory_rule_id')
    )
    op.create_index(op.f('ix_accessory_rule_accessory_rule_id'), 'accessory_rule', ['accessory_rule_id'], unique=False)
    op.create_table('configuration_rule',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('series_id', sa.String(), nullable=True),
    sa.Column('ats_included', sa.Boolean(), nullable=True),
    sa.Column('size_class', sa.String(), nullable=True),
    sa.Column('load_count', sa.Integer(), nullable=True),
    sa.Column('recommended_enclosure_option_id', sa.String(), nullable=True),
    sa.Column('alternative_enclosure_option_ids', sa.String(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recommended_enclosure_option_id'], ['enclosure_option.enclosure_option_id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.series_id'], ),
    sa.ForeignKeyConstraint(['size_class'], ['size_class.size_class'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_configuration_rule_rule_id'), 'configuration_rule', ['rule_id'], unique=False)
    op.create_table('drawing_template',
    sa.Column('drawing_template_id', sa.String(), nullable=False),
    sa.Column('series_id', sa.String(), nullable=True),
    sa.Column('load_count', sa.Integer(), nullable=True),
    sa.Column('source_status', sa.String(), nullable=True),
    sa.Column('template_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.series_id'], ),
    sa.PrimaryKeyConstraint('drawing_template_id')
    )
    op.create_index(op.f('ix_drawing_template_drawing_template_id'), 'drawing_template', ['drawing_template_id'], unique=False)
    op.create_table('starter_option',
    sa.Column('starter_option_id', sa.String(), nullable=False),
    sa.Column('series_id', sa.String(), nullable=True),
    sa.Column('rated_load_power_kw', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('thermal_relay_range_text', sa.String(), nullable=True),
    sa.Column('thermal_relay_min_a', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('thermal_relay_max_a', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('nominal_circuit_breaker_current_a', sa.Integer(), nullable=True),
    sa.Column('magnetic_cb_part_number', sa.String(), nullable=True),
    sa.Column('contactor_part_number', sa.String(), nullable=True),
    sa.Column('overload_part_number', sa.String(), nullable=True),
    sa.Column('size_class', sa.String(), nullable=True),
    sa.Column('data_quality_flag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contactor_part_number'], ['component_catalog.part_number'], ),
    sa.ForeignKeyConstraint(['magnetic_cb_part_number'], ['component_catalog.part_number'], ),
    sa.ForeignKeyConstraint(['overload_part_number'], ['component_catalog.part_number'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.series_id'], ),
    sa.ForeignKeyConstraint(['size_class'], ['size_class.size_class'], ),
    sa.PrimaryKeyConstraint('starter_option_id')
    )
    op.create_index(op.f('ix_starter_option_starter_option_id'), 'starter_option', ['starter_option_id'], unique=False)
    op.create_table('configuration',
    sa.Column('config_id', sa.String(), nullable=False),
    sa.Column('starter_option_id', sa.String(), nullable=True),
    sa.Column('series_id', sa.String(), nullable=True),
    sa.Column('load_count', sa.Integer(), nullable=True),
    sa.Column('ats_included', sa.Boolean(), nullable=True),
    sa.Column('selected_enclosure_option_id', sa.String(), nullable=True),
    sa.Column('drawing_template_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['drawing_template_id'], ['drawing_template.drawing_template_id'], ),
    sa.ForeignKeyConstraint(['selected_enclosure_option_id'], ['enclosure_option.enclosure_option_id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.series_id'], ),
    sa.ForeignKeyConstraint(['starter_option_id'], ['starter_option.starter_option_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index(op.f('ix_configuration_config_id'), 'configuration', ['config_id'], unique=False)
    op.create_table('bom_line',
    sa.Column('bom_line_id', sa.String(), nullable=False),
    sa.Column('config_id', sa.String(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('item_category', sa.String(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['configuration.config_id'], ),
    sa.PrimaryKeyConstraint('bom_line_id')
    )
    op.create_index(op.f('ix_bom_line_bom_line_id'), 'bom_line', ['bom_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bom_line_bom_line_id'), table_name='bom_line')
    op.drop_table('bom_line')
    op.drop_index(op.f('ix_configuration_config_id'), table_name='configuration')
    op.drop_table('configuration')
    op.drop_index(op.f('ix_starter_option_starter_option_id'), table_name='starter_option')
    op.drop_table('starter_option')
    op.drop_index(op.f('ix_drawing_template_drawing_template_id'), table_name='drawing_template')
    op.drop_table('drawing_template')
    op.drop_index(op.f('ix_configuration_rule_rule_id'), table_name='configuration_rule')
    op.drop_table('configuration_rule')
    op.drop_index(op.f('ix_accessory_rule_accessory_rule_id'), table_name='accessory_rule')
    op.drop_table('accessory_rule')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_size_class_size_class'), table_name='size_class')
    op.drop_table('size_class')
    op.drop_index(op.f('ix_series_series_id'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_enclosure_option_enclosure_option_id'), table_name='enclosure_option')
    op.drop_table('enclosure_option')
    op.drop_index(op.f('ix_data_quality_issue_issue_id'), table_name='data_quality_issue')
    op.drop_table('data_quality_issue')
    op.drop_index(op.f('ix_component_catalog_part_number'), table_name='component_catalog')
    op.drop_table('component_catalog')
    op.drop_index(op.f('ix_application_option_matrix_id'), table_name='application_option_matrix')
    op.drop_table('application_option_matrix')
    op.drop_index(op.f('ix_application_io_template_id'), table_name='application_io_template')
    op.drop_table('application_io_template')
    op.drop_index(op.f('ix_application_alarm_template_id'), table_name='application_alarm_template')
    op.drop_table('application_alarm_template')
    op.drop_index(op.f('ix_accessory_catalog_part_number'), table_name='accessory_catalog')
    op.drop_index(op.f('ix_accessory_catalog_accessory_id'), table_name='accessory_catalog')
    op.drop_table('accessory_catalog')
    # ### end Alembic commands ###
