"""add alternative enclosures to configurations

Revision ID: 9c00b9fef082
Revises: 9e6a085d4d60
Create Date: 2026-05-04 15:02:46.913413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c00b9fef082"
down_revision: Union[str, Sequence[str], None] = "9e6a085d4d60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configuration",
        sa.Column("alternative_enclosure_option_id", sa.String(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("alternative_enclosure_ref", sa.String(), nullable=True),
    )
    op.add_column(
        "configuration",
        sa.Column("outdoor_alternative_enclosure_ref", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configuration", "outdoor_alternative_enclosure_ref")
    op.drop_column("configuration", "alternative_enclosure_ref")
    op.drop_column("configuration", "alternative_enclosure_option_id")
    # ### end Alembic commands ###
