"""add alternatives to enclosure catalog

Revision ID: 9e6a085d4d60
Revises: d3d40a61cd15
Create Date: 2026-04-30 14:37:24.355961

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e6a085d4d60"
down_revision: Union[str, Sequence[str], None] = "d3d40a61cd15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "enclosure_option",
        sa.Column("alternative_catalog_ref", sa.String(), nullable=True),
    )
    op.add_column(
        "enclosure_option",
        sa.Column("outdoor_alternative_catalog_ref", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("enclosure_option", "outdoor_alternative_catalog_ref")
    op.drop_column("enclosure_option", "alternative_catalog_ref")
    # ### end Alembic commands ###
