"""Add ProjectMetadata table

Revision ID: b79635c9f2fc
Revises: 5f78f076c92a
Create Date: 2026-05-27 14:57:56.336762

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b79635c9f2fc"
down_revision: Union[str, Sequence[str], None] = "5f78f076c92a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

"""
__tablename__ = "project_metadata"
    id = Column(Integer, primary_key=True, index=True)
    config_id = Column(String, ForeignKey("configuration.config_id"), unique=True)
    project_name = Column(String)
    client = Column(String)
    technical_manager = Column(String)
    location = Column(String)
    date = Column(String)
    notes = Column(String)
    enclosure_ref = Column(String)
    communication = Column(String)
    plc = Column(Boolean)
    scada = Column(Boolean)
"""


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "project_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_name", sa.String(), nullable=True),
        sa.Column("config_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["config_id"], ["configuration.config_id"]),
        sa.Column("client", sa.String(), nullable=True),
        sa.Column("technical_manager", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("enclosure_ref", sa.String(), nullable=True),
        sa.Column("communication", sa.String(), nullable=True),
        sa.Column("plc", sa.Boolean(), nullable=True),
        sa.Column("scada", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_metadata")
    # ### end Alembic commands ###
