"""schema_coherence_updates

Revision ID: d3d40a61cd15
Revises: 7684c9de6efd
Create Date: 2026-03-19 13:05:56.606327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d40a61cd15'
down_revision: Union[str, Sequence[str], None] = '7684c9de6efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_line', sa.Column('uom', sa.String(), nullable=True))
    op.add_column('bom_line', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('bom_line', sa.Column('source_id', sa.String(), nullable=True))
    op.add_column('component_catalog', sa.Column('used_in_starter_option_ids', sa.String(), nullable=True))
    op.add_column('component_catalog', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('rated_load_power_kw', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('configuration', sa.Column('size_class', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('magnetic_cb_part_number', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('magnetic_cb_qty', sa.Integer(), nullable=True))
    op.add_column('configuration', sa.Column('contactor_part_number', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('contactor_qty', sa.Integer(), nullable=True))
    op.add_column('configuration', sa.Column('overload_part_number', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('overload_qty', sa.Integer(), nullable=True))
    op.add_column('configuration', sa.Column('selected_enclosure_ref', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('selected_enclosure_layout_dims_mm', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('selected_enclosure_catalog_size', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('mounting_type', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('bom_scope', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('core_device_type', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('core_device_part_number', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('core_device_qty', sa.Integer(), nullable=True))
    op.add_column('configuration', sa.Column('core_device_source_id', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('line_contactor_role', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('bypass_strategy', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('bypass_contactor_part_number', sa.String(), nullable=True))
    op.add_column('configuration', sa.Column('bypass_contactor_qty', sa.Integer(), nullable=True))
    op.add_column('configuration_rule', sa.Column('recommended_catalog_ref', sa.String(), nullable=True))
    op.add_column('configuration_rule', sa.Column('recommended_layout_dims_mm', sa.String(), nullable=True))
    op.add_column('configuration_rule', sa.Column('lookup_key', sa.String(), nullable=True))
    op.add_column('configuration_rule', sa.Column('recommended_summary', sa.String(), nullable=True))
    op.add_column('drawing_template', sa.Column('engineering_note', sa.String(), nullable=True))
    op.add_column('enclosure_option', sa.Column('description', sa.String(), nullable=True))
    op.add_column('enclosure_option', sa.Column('data_quality_note', sa.String(), nullable=True))
    op.add_column('starter_option', sa.Column('availability_status', sa.String(), nullable=True))
    op.add_column('starter_option', sa.Column('selection_basis', sa.String(), nullable=True))
    op.add_column('starter_option', sa.Column('product_range', sa.String(), nullable=True))
    op.add_column('starter_option', sa.Column('controller_dims_wxhxd_mm', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('starter_option', 'controller_dims_wxhxd_mm')
    op.drop_column('starter_option', 'product_range')
    op.drop_column('starter_option', 'selection_basis')
    op.drop_column('starter_option', 'availability_status')
    op.drop_column('enclosure_option', 'data_quality_note')
    op.drop_column('enclosure_option', 'description')
    op.drop_column('drawing_template', 'engineering_note')
    op.drop_column('configuration_rule', 'recommended_summary')
    op.drop_column('configuration_rule', 'lookup_key')
    op.drop_column('configuration_rule', 'recommended_layout_dims_mm')
    op.drop_column('configuration_rule', 'recommended_catalog_ref')
    op.drop_column('configuration', 'bypass_contactor_qty')
    op.drop_column('configuration', 'bypass_contactor_part_number')
    op.drop_column('configuration', 'bypass_strategy')
    op.drop_column('configuration', 'line_contactor_role')
    op.drop_column('configuration', 'core_device_source_id')
    op.drop_column('configuration', 'core_device_qty')
    op.drop_column('configuration', 'core_device_part_number')
    op.drop_column('configuration', 'core_device_type')
    op.drop_column('configuration', 'bom_scope')
    op.drop_column('configuration', 'mounting_type')
    op.drop_column('configuration', 'selected_enclosure_catalog_size')
    op.drop_column('configuration', 'selected_enclosure_layout_dims_mm')
    op.drop_column('configuration', 'selected_enclosure_ref')
    op.drop_column('configuration', 'overload_qty')
    op.drop_column('configuration', 'overload_part_number')
    op.drop_column('configuration', 'contactor_qty')
    op.drop_column('configuration', 'contactor_part_number')
    op.drop_column('configuration', 'magnetic_cb_qty')
    op.drop_column('configuration', 'magnetic_cb_part_number')
    op.drop_column('configuration', 'size_class')
    op.drop_column('configuration', 'rated_load_power_kw')
    op.drop_column('component_catalog', 'notes')
    op.drop_column('component_catalog', 'used_in_starter_option_ids')
    op.drop_column('bom_line', 'source_id')
    op.drop_column('bom_line', 'source_type')
    op.drop_column('bom_line', 'uom')
    # ### end Alembic commands ###
