from __future__ import annotations
from decimal import Decimal
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class SelectedAssetNode(BaseModel):
    id: str = Field(..., description="Asset identifier (stable machine id)")
    label: str = Field(..., description="Human readable label")
    selected: bool = Field(False, description="Whether this node is selected")
    children: List[SelectedAssetNode] = Field(default_factory=list)

    model_config = ConfigDict(extra="forbid")


SelectedAssetNode.model_rebuild()  # ensure recursive model is wired


# --- INPUT SCHEMAS ---
class DigitalTwinRequest(BaseModel):
    series_id: str = Field(..., description="E.g., DOL, YD, VFD")
    series_name: Optional[str] = Field(
        None, description="Human readable series name (for better UX, optional)"
    )
    motor_power_kw: Decimal = Field(..., description="Rated power in kW")
    load_count: int = Field(
        ..., gt=0, description="Number of parallel starters/feeders"
    )
    ats_included: bool = Field(
        False, description="Whether an Auto Transfer Switch is included"
    )
    control_mode: Optional[str] = Field(
        "Local", description="Control modality (Local, Remote, Auto)"
    )
    ip_rating: Optional[str] = Field("IP54", description="Desired enclosure IP rating")
    communication: Optional[str] = Field(
        "No", description="Network protocol (No, ModbusTCP, ProfiNet)"
    )
    plc_included: Optional[str] = Field(
        "No", description="PLC inclusion ('YES' or 'No')"
    )
    scada_included: Optional[str] = Field(
        "No", description="SCADA inclusion ('YES' or 'No')"
    )
    selected_assets: List[SelectedAssetNode] = Field(
        default_factory=list, description="Nested asset tree (ids + labels + selected)"
    )
    multi_line_diagram_b64: Optional[str] = Field(
        None,
        description="Base64 encoded string of the multi line diagram image generated by frontend",
    )
    reference_architecture_b64: Optional[str] = Field(
        None,
        description="Base64 encoded string of the reference architecture image generated by frontend",
    )
    environment: Optional[str] = Field(
        "Indoor", description="Installation environment (Indoor, Outdoor, Not sure)"
    )
    enclosure_ref: Optional[str] = Field(
        None, description="Reference for the selected enclosure option, if any"
    )


# --- OUTPUT SCHEMAS (DIGITAL TWIN) ---
class TwinBomLine(BaseModel):
    line_no: int
    item_category: str
    part_number: Optional[str] = None
    description: Optional[str] = None
    qty: Decimal
    uom: str
    item: Optional[str] = None
    key_selection_notes: Optional[str] = None
    condition: Optional[str] = None  # For conditional items like fans/grills


class TwinComponent(BaseModel):
    part_number: str
    description: Optional[str] = None
    qty: Decimal
    item_category: str = Field(
        ..., description="E.g., Magnetic CB, Contactor, Overload"
    )


class TwinAccessory(BaseModel):
    part_number: str
    description: Optional[str] = None
    qty: Decimal
    category: Optional[str] = None


class TwinEnclosure(BaseModel):
    catalog_ref: str
    dimensions_mm: str = Field(..., description="Format: HxWxD")
    mounting_type: str
    # Added after enclosure alternative updates
    alternative_ref: Optional[str] = None
    outdoor_alternative_ref: Optional[str] = None


class TwinIO(BaseModel):
    tag: str
    description: str
    signal_type: str
    interface: str
    ip_address: Optional[str] = None


class TwinAlarm(BaseModel):
    code: str
    source_tag: str
    condition: str
    priority: str
    operator_message: str


class TwinOption(BaseModel):
    category: str
    name: str
    is_base: bool
    spec_text: Optional[str] = None
    engineering_notes: Optional[str] = None


class DigitalTwinResponse(BaseModel):
    config_id: str = Field(..., description="Unique ID for this configuration result")
    series_id: str
    series_name: Optional[str] = None
    motor_power_kw: Decimal
    load_count: int
    enclosure: TwinEnclosure
    components: List[TwinComponent]
    accessories: List[TwinAccessory]
    drawing_template_id: Optional[str] = None
    notes: Optional[str] = None
    communication: Optional[str] = "No"
    bypass_strategy: Optional[str] = None
    bypass_contactor_part_number: Optional[str] = None
    plc_included: Optional[str] = "No"
    scada_included: Optional[str] = "No"
    selected_assets: List[SelectedAssetNode] = Field(default_factory=list)
    multi_line_diagram_b64: Optional[str] = None
    reference_architecture_b64: Optional[str] = None
    environment: Optional[str] = None

    # New Application Data Sheets
    bom_lines: List[TwinBomLine] = Field(default_factory=list)
    network_plan: List[TwinIO] = Field(default_factory=list)
    alarm_list: List[TwinAlarm] = Field(default_factory=list)
    option_matrix: List[TwinOption] = Field(default_factory=list)

    model_config = ConfigDict(from_attributes=True)
