import React from "react";
import { useNavigate } from "react-router-dom";

function TermsPage() {
  const navigate = useNavigate();

  return (
    <div className="booster" style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', padding: 'var(--space-xl)' }}>
      <header className="booster__header fade-in" style={{ marginBottom: 'var(--space-xl)' }}>
        <div className="booster__header-left">
          <h1 className="booster__title">Terms of Use</h1>
          <p className="booster__subtitle">Legal agreement and usage policies.</p>
        </div>
        <div className="booster__header-right">
          <button className="btn-secondary" onClick={() => navigate("/")}>
            ← Go to Home
          </button>
        </div>
      </header>

      <main className="fade-in fade-in-delay-1" style={{ flex: 1, display: 'flex', justifyContent: 'center', marginBottom: 'var(--space-xl)' }}>
        <section className="glass-card" style={{ maxWidth: '800px', width: '100%', padding: 'var(--space-xl)', color: 'var(--text-primary)' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: 'var(--space-md)', borderBottom: '1px solid var(--border-glass)', paddingBottom: 'var(--space-sm)' }}>
            1. Acceptance of Terms
          </h2>
          <p style={{ marginBottom: 'var(--space-lg)', fontSize: '0.95rem', lineHeight: '1.6' }}>
            By accessing and using the Motor Control Asset Library configuration tool, you agree to comply with and be bound by these Terms of Use. If you do not agree to these terms, please do not use this application.
          </p>

          <h2 style={{ fontSize: '1.5rem', marginBottom: 'var(--space-md)', borderBottom: '1px solid var(--border-glass)', paddingBottom: 'var(--space-sm)' }}>
            2. Permitted Use & Engineering Disclaimer
          </h2>
          <p style={{ marginBottom: 'var(--space-lg)', fontSize: '0.95rem', lineHeight: '1.6' }}>
            The schematics, specifications, data sheets, and BOM lists generated by this application are early-stage engineering design templates. They do not constitute final project engineering designs. All details, including product selections, protection ratings, heat dissipation, short-circuit calculations, and local code compliance, must be verified by a qualified Professional Engineer (PE) or System Integrator before procurement or installation.
          </p>

          <h2 style={{ fontSize: '1.5rem', marginBottom: 'var(--space-md)', borderBottom: '1px solid var(--border-glass)', paddingBottom: 'var(--space-sm)' }}>
            3. Intellectual Property
          </h2>
          <p style={{ marginBottom: 'var(--space-lg)', fontSize: '0.95rem', lineHeight: '1.6' }}>
            This application and its original content, features, and functionality are and will remain the exclusive property of Schneider Electric and its licensors. Content generated for users may be copy-pasted and used in custom design specifications for commercial engineering project submittals.
          </p>

          <h2 style={{ fontSize: '1.5rem', marginBottom: 'var(--space-md)', borderBottom: '1px solid var(--border-glass)', paddingBottom: 'var(--space-sm)' }}>
            4. Limitation of Liability
          </h2>
          <p style={{ marginBottom: 'var(--space-lg)', fontSize: '0.95rem', lineHeight: '1.6' }}>
            Schneider Electric, its directors, employees, partners, agents, suppliers, or affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or reliance upon any drawings, text specifications, or components selected through this tool.
          </p>
        </section>
      </main>
    </div>
  );
}

export default TermsPage;
