import React from "react";
import { useNavigate } from "react-router-dom";
import "./TermsPage.css";

function TermsPage() {
  const navigate = useNavigate();

  return (
    <main className="terms-page">
      <section className="terms-page__content">
        <button
          type="button"
          className="terms-page__back"
          onClick={() => navigate("/")}
        >
          ← Go to Home
        </button>

        <h1>Terms of Use</h1>
        <p className="terms-page__intro">
          Please read these Terms of Use carefully before using this
          configuration and design-assistance application.
        </p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using this application, you agree to be bound by these
          Terms of Use. If you do not agree with these terms, you must not use
          the application or rely on any output generated by it.
        </p>

        <h2>2. Purpose of the Application</h2>
        <p>
          This application is intended to provide early-stage configuration
          assistance and reusable project-starting assets, such as indicative
          specifications, reference architectures, schematic templates, data
          sheets, bills of materials, and related documentation.
        </p>
        <p>
          The application is a design-support tool only. It does not provide
          final engineering, procurement, construction, installation,
          commissioning, safety, legal, regulatory, or compliance approval.
        </p>

        <h2>3. Engineering Disclaimer</h2>
        <p>
          All outputs generated by the application are preliminary and generic
          in nature. They may not account for all project-specific conditions,
          including but not limited to site environment, short-circuit levels,
          thermal performance, cable lengths, coordination studies, safety
          requirements, local standards, utility requirements, end-user
          specifications, cybersecurity requirements, or applicable laws and
          regulations.
        </p>
        <p>
          Before any output is used for procurement, construction, installation,
          operation, commissioning, or submission to an authority or client, it
          must be independently reviewed, completed, validated, and approved by
          suitably qualified professionals, such as licensed engineers, system
          integrators, panel builders, safety specialists, or other competent
          technical experts.
        </p>

        <h2>4. User Responsibility</h2>
        <p>
          You are solely responsible for the projects, selections, designs,
          documents, assumptions, calculations, and decisions created, modified,
          exported, copied, or otherwise used through the application. You are
          responsible for verifying the accuracy, suitability, completeness,
          safety, interoperability, performance, and compliance of all outputs
          before use.
        </p>
        <p>
          You must ensure that any final design complies with all applicable
          laws, regulations, codes, standards, contractual requirements, site
          rules, and end-user requirements. You must not treat the application
          output as a substitute for professional judgment, detailed
          engineering, risk assessment, or formal approval processes.
        </p>

        <h2>5. Product and Component Information</h2>
        <p>
          Any product references, component selections, ratings, dimensions,
          quantities, or technical characteristics generated or displayed by the
          application are indicative only. Availability, compatibility,
          certification, performance, and final part numbers must be confirmed
          against the applicable manufacturer documentation, local catalogues,
          project requirements, and site conditions before use.
        </p>
        <p>
          The inclusion or generation of a product, component, architecture, or
          document does not constitute a recommendation, warranty, guarantee, or
          confirmation that it is suitable for a particular project or purpose.
        </p>

        <h2>6. No Warranty</h2>
        <p>
          The application and all outputs are provided on an “as is” and “as
          available” basis. To the maximum extent permitted by law, no
          warranties or representations are made, whether express, implied,
          statutory, or otherwise, including warranties of accuracy,
          completeness, merchantability, fitness for a particular purpose,
          non-infringement, availability, compatibility, or error-free
          operation.
        </p>

        <h2>7. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, the application provider and
          its owners, directors, employees, contractors, licensors, suppliers,
          and affiliates shall not be liable for any direct, indirect,
          incidental, special, consequential, punitive, exemplary, or economic
          damages, including loss of profits, loss of revenue, loss of business,
          loss of data, project delays, equipment damage, system downtime,
          regulatory penalties, third-party claims, or costs of replacement
          goods or services arising from or related to your use of, inability to
          use, or reliance on the application or its outputs.
        </p>

        <h2>8. User Inputs and Generated Outputs</h2>
        <p>
          You are responsible for the accuracy and legality of all information,
          assumptions, files, parameters, and data that you enter into or upload
          to the application. Outputs are generated based on the information
          provided and may be incomplete or incorrect if the inputs are
          incomplete, inaccurate, outdated, or unsuitable.
        </p>
        <p>
          Subject to these Terms of Use, you may use generated outputs as
          editable starting points for your own project documentation. You
          remain solely responsible for reviewing, modifying, validating,
          approving, and controlling the final content before use.
        </p>

        <h2>9. Intellectual Property</h2>
        <p>
          The application, including its software, user interface, workflows,
          templates, logic, databases, and original content, is protected by
          applicable intellectual property laws and remains the property of its
          respective owner or licensors. No rights are granted except as
          expressly permitted by these Terms of Use.
        </p>
        <p>
          You must not copy, reverse engineer, decompile, modify, reproduce,
          distribute, resell, or create competing services based on the
          application except where expressly authorized in writing or permitted
          by applicable law.
        </p>

        <h2>10. Prohibited Use</h2>
        <p>
          You must not use the application in a manner that is unlawful,
          misleading, harmful, abusive, security-compromising, or inconsistent
          with these Terms of Use. You must not attempt to bypass access
          controls, interfere with the application, upload malicious content, or
          use generated outputs without required professional review and project
          validation.
        </p>

        <h2>11. Changes to the Application and Terms</h2>
        <p>
          The application and these Terms of Use may be updated, modified,
          suspended, or discontinued at any time without prior notice. Continued
          use of the application after changes are made constitutes acceptance
          of the updated terms.
        </p>

        <h2>12. General</h2>
        <p>
          If any provision of these Terms of Use is found to be invalid or
          unenforceable, the remaining provisions shall remain in effect. These
          Terms of Use constitute the entire agreement between you and the
          application provider regarding use of the application, unless a
          separate written agreement applies.
        </p>
      </section>
    </main>
  );
}

export default TermsPage;
